# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require File.expand_path('../config/application', __FILE__)
require 'rake'

# rails doesn't work with rake 0.9.0 correct, so we had to add this (kswope)
class Rails::Application
  include Rake::DSL if defined?(Rake::DSL)
end

RailsRoot::Application.load_tasks
